#!/usr/bin/env python3
"""Regenerate gigabpe/src/unicode_tables.rs.

The tables define the regex classes \\p{L} and \\p{N} as used by the GPT-2
pretokenizer pattern. They are derived from HuggingFace's own ByteLevel
pretokenizer rather than from a Unicode database, because parity is defined
against HF and the two drift: Python 3.12's `unicodedata` is Unicode 15,
while the `regex` crate HF uses ships Unicode 16, which disagree on at least
U+1C89, U+1C8A and U+A7CB..U+A7CD. Deriving from HF makes the tables correct
by construction for whatever version HF was built against.

Classification probes, using the fact that ` ?\\p{L}+` and ` ?\\p{N}+` each
match a run of one class:

  "a" + c  -> one token  iff  c is \\p{L}
  "1" + c  -> one token  iff  c is \\p{N}

Rust's char::is_alphabetic (the Alphabetic property) is not \\p{L}: it also
covers Nl and Other_Alphabetic, so it cannot be substituted.

Usage:
  python3 scripts/gen_unicode_tables.py > gigabpe/src/unicode_tables.rs
"""
import sys

from tokenizers import pre_tokenizers

HF = pre_tokenizers.ByteLevel(add_prefix_space=False, use_regex=True)


def scalars():
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        yield cp


def classify():
    """Returns (letters, numbers) as sets of codepoints."""
    letters, numbers = set(), set()
    for cp in scalars():
        c = chr(cp)
        if len(HF.pre_tokenize_str("a" + c)) == 1:
            letters.add(cp)
        elif len(HF.pre_tokenize_str("1" + c)) == 1:
            numbers.add(cp)
    return letters, numbers


def to_ranges(cps):
    out = []
    start = prev = None
    for cp in sorted(cps):
        if start is None:
            start = prev = cp
        elif cp == prev + 1:
            prev = cp
        else:
            out.append((start, prev))
            start = prev = cp
    if start is not None:
        out.append((start, prev))
    return out


def main():
    print("classifying codepoints against HF...", file=sys.stderr)
    letters, numbers = classify()
    lr, nr = to_ranges(letters), to_ranges(numbers)
    print(f"  {len(letters)} letters in {len(lr)} ranges, "
          f"{len(numbers)} numbers in {len(nr)} ranges", file=sys.stderr)

    print("//! Unicode character classes for the GPT-2 pretokenizer pattern.")
    print("//!")
    print("//! Generated by scripts/gen_unicode_tables.py by probing HuggingFace's")
    print("//! ByteLevel pretokenizer directly. Do not edit by hand.")
    print("//!")
    print("//! Derived from HF rather than from a Unicode database on purpose:")
    print("//! parity is defined against HF, and the versions drift (Python 3.12")
    print("//! is Unicode 15, the regex crate HF uses is Unicode 16; they")
    print("//! disagree on U+1C89, U+1C8A and U+A7CB..U+A7CD). Rust's")
    print("//! char::is_alphabetic is also not \\\\p{L} — it includes Nl and")
    print("//! Other_Alphabetic, which the pattern treats differently.")
    print()
    # ASCII fast path: web text is overwhelmingly ASCII, and a binary search
    # over ~700 ranges per character dominated phase 1 at scale.
    for name, cps in (("LETTER", letters), ("NUMBER", numbers)):
        bits = ["true" if cp in cps else "false" for cp in range(128)]
        print(f"static ASCII_{name}: [bool; 128] = [")
        for i in range(0, 128, 8):
            print("    " + ", ".join(bits[i:i + 8]) + ",")
        print("];")
        print()

    for name, rs in (("LETTER", lr), ("NUMBER", nr)):
        print(f"pub static {name}_RANGES: [(u32, u32); {len(rs)}] = [")
        for a, b in rs:
            print(f"    (0x{a:04X}, 0x{b:04X}),")
        print("];")
        print()
    print(TAIL)


TAIL = '''#[inline]
fn in_ranges(c: char, ranges: &[(u32, u32)]) -> bool {
    let cp = c as u32;
    ranges
        .binary_search_by(|&(lo, hi)| {
            if cp < lo {
                std::cmp::Ordering::Greater
            } else if cp > hi {
                std::cmp::Ordering::Less
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

/// True if `c` matches the pattern's `\\p{L}` class.
#[inline]
pub fn is_letter(c: char) -> bool {
    let cp = c as u32;
    if cp < 128 {
        return ASCII_LETTER[cp as usize];
    }
    in_ranges(c, &LETTER_RANGES)
}

/// True if `c` matches the pattern's `\\p{N}` class.
#[inline]
pub fn is_number(c: char) -> bool {
    let cp = c as u32;
    if cp < 128 {
        return ASCII_NUMBER[cp as usize];
    }
    in_ranges(c, &NUMBER_RANGES)
}'''


if __name__ == "__main__":
    main()
